- src/winusb
Hello Slacka,
on my Gentoo Linux "mount -o loop" needs "-t iso9660" parameter as well. I'm not sure if it works without it in different environments - but this is the most reliable way for iso images.
Winusb is a great script, thanks for that!
Jaromir
> fix: mount -o loop needs type param

- src/winusb
Some flash devices have partition names that append p1, p2, etc to the device name instead of simply an integer.  This allows those to be recognized.
> Fixes partition lookup when formatting the entire device

- src/winusb
Reverts slacka/WinUSB#2
Not all ISOs use ISO9660 file systems.
> Revert "fix: mount -o loop needs type param"

- src/winusb
GRUB installation command will fail if user's platform is not
i386-pc(thus x86_64-efi users will encounter "grub2-install: error:
/media/winusb_target_* doesn't look like an EFI partition." error), this
commit fixes the problem by specifying GRUB install mode/platform to
i386-pc.
NOTE:
* This patch is not fully tested, beware of regressions!
* This patch didn't implement test to check if GRUB's i386-pc platform
files exists in user's system.
> Specify i386-pc(MBR) mode when installing GRUB, fixes #1

- src/winusb
The `ls --color=no -1 /dev/sdc | grep -ve '/dev/sdc$'` command failed to
find any partitions after reading partition table, it seems that the
system needs more time to repopulate the new device nodes.
```
+ parted --align cylinder -s /dev/sdc mkpart primary 1MB 31.6GB
+ blockdev --rereadpt /dev/sdc
+ partprobe /dev/sdc
++ grep -ve '/dev/sdc$'
++ ls --color=no -1 /dev/sdc
+ partition=
```
This commit fixes the issue by pausing 3 seconds before detecting
partitions, however this fix should be improved by using more reliable
method to ensure that the system is ready.
> cli: fix winusb prematurely ended after the "Formating device..." message, fixes #10

- src/winusb
Currently `LANG` environmental variable is set to ""(empty string) when
running commands.
According to GNU Gettext documentation(`$ info gettext "The LANGUAGE
variable"`):
```
Note: The variable ‘LANGUAGE’ is ignored if the locale is set to ‘C’. In
other words, you have to first enable localization, by setting ‘LANG’
(or ‘LC_ALL’) to a value other than ‘C’, before you can use a language
priority list through the ‘LANGUAGE’ variable.
```
I believe setting to "C" is the proper way to disable localization.
> Set LANG="C" instead when running commands, fixes #20

- debian/control
grub-pc-bin package is needed for EFI platform user to install PC/MBR
style GRUB boot loader.
We'll also need to depend on grub-efi-bin after UEFI booting support is
implemented in the future.
> Debian packaging: Depend on grub-pc-bin, fixes #22

- src/winusb
It seems that the use of `--root-directory` option is deprecated in
`grub-install` command(there's no trace on the manual and manpage,
*although the option is still accepted with unknown reason*).
**UPDATE:** This option appears on the [GRUB (legacy?) 0.97
manual](https://www.gnu.org/software/grub/manual/legacy/Invoking-
grub_002dinstall.html) but not on 2.00's
We should replace it with the existing `--boot-directory` instead.
NOTE:
* Now grub will be install under $TARGET_MOUNTPOINT/grub
* This patch also removes
```
if [ -d "$partitionMountPath/BOOT" ]; then mv "$partitionMountPath/BOOT"
"$partitionMountPath/boot"; fi
if [ -d "$partitionMountPath/Boot" ]; then mv "$partitionMountPath/Boot"
"$partitionMountPath/boot"; fi
```
as grub files no longer being placed under …
> Obselute of using --root-directory on grub-install, fixes #16

- src/winusb
This is a derived issue of #15 , UEFI requires that the removable boot-able device using FAT~~32~~ filesystem(instead of NTFS, which WinUSB is currently using).
This commit deals with issue by switching the target filesystem to FAT:
* Replace NTFS format command to FAT's one(while dropping some non-critical options that is not available).
* Modify GRUB config to be FAT-compatible
* It seems that NTFS format tool will install a BOOTMGR-compatible VBR while FAT's tool doesn't, so I changed to use GRUB's `ntldr` command instead of `chainloader +1` command
* Of course, replace all messages with NTFS to FAT
After this commit, WinUSB should automagically supports UEFI boot(and also SecureBoot as we're now using GRUB as PC/MBR bootloader and Windows signed BOOTMGR as EFI bootloader, whether to …
> cli: Switch to use FAT filesystem, fixes #18, #15, #6

- src/winusb
Oops, I forgot to fix grub.cfg path to /grub/grub.cfg on commit 3f91011, this patch fixes it.
GitHub-Issue: #26 
> Fix regression: grub.cfg path not fixed on commit 3f91011("Obselute of using --root-directory on grub-install, fixes #16"), fixes #26

- src/winusb
There's no need to "remove all partition" when the user already decided
to `--format` the drive, just create a new partition table and overwrite
the old one.
> Optimize "# remove all partitions" logic, create a new partition table instead, fixes #13

- src/winusb
This patch fixes the following issues:
1. Depend on parsing Parted output for deciding the maximum size of the
partition(may break if parted change its output)
2. Using a partition alignment that is not friendly to flash
memory(lower transfer speed and potentially higher memory cell wear-off,
refer http://lwn.net/Articles/428584/ ).
3. Not specifying partition type code(and Parted defaults it to
EXT*(83))
by:
1. Using '-1s' notation to specify the last sector of the drive.
2. Aligning partition to 4MiB boundary
3. Specifying FAT32 partition type
Reference:
* GNU Parted infodoc - 2.4.5 mkpart
> cli: Improve partition creation code

- debian/control
This commit:
* Adds WxWidgets 3 as one of WinUSB's build dependencies
* Specify WxWidgets 2's accepted version according to configure script
output.
> Update Debian build dependencies

- debian/control
Since adca4024 the debian control file depends on either grub-pc or grub-efi, however currently in Ubuntu grub-efi *only* depends on grub-efi-amd64 but not grub-efi-i386, which could cause dependency unsatisfied issues on i386-efi systems.
This commits changes the dependency to depend on grub-pc OR grub-efi-amd64 OR grub-efi-i386, to fix this problem, unfortunately I don't have any 32-bit UEFI system to test this patch.
> Update debian control file to depend on either grub-efi-i386 OR grub-efi-amd64

- src/winusb
Currently $neededSpace is added 30MB(1000 * 1000 * 30byte) instead of 10MB(1000 * 1000 * 10byte) like the comment indicated.
This patch change the value back to 10MB, on my system the grub installation only using 4.5MB space so this value is sufficient.
Also the comment has been improved.
> src/winusb: fix neededSpace calculation

- src/locale/default.po
- src/locale/fr/LC_MESSAGES/trad.po
Currently the message catalog's project id is set to "memwrite", which apparently is Congelli501's [another project](http://en.congelli.eu/prog_info_memwrite.html)'s id.  This commit reset the id to "winusb"
> Fix gettext message catalog project id

- src/winusb
Currently the examples printed by running `winusb --help` is actually wrong since the command-line options/switches are missing, this patch fixes them.
Thanks to @larsnystrom for bringing this problem to front of my eyes.
> src/winusb - Fix command-line argument examples, fixes #37 ...?

- src/MainPanel.cpp
Currently the error string are inserted as an item of the target device list, which may causes `winusbgui` selecting the wrong target device to --format because of [off-by-N error](https://en.wikipedia.org/wiki/Off-by-one_error).
`winusbgui` currently calls two external script, namely `src/data/listUsb` and `src/data/listDvdDrive` to acquire connected hardware information, which output to stdout with the following format:
```
<block device path>
<block device path> - <disk model acquired from sysfs> - <disk model acquired from `parted -s`>
```
Then `winusbgui` collects the first row to a C++ STL &lt;vector&gt; and a second row to a wxListBox `m_(usbStick | dvdDrive)List` and when installation triggered, retrieve the &lt;block device path&gt; according to the index of selected item in …
> src/MainPanel.cpp - redirect error stream to /dev/null, fix possible off-by-N error, fixes #57

- debian/control
- src/winusb
This adds UEFI boot support for Windows 7.  In PR #25 only added that for Windows >=8:
> According to my test on Windows 7/Windows 10 ISO I suspect that UEFI support will be compatible with Windows >=8(Although Windows 7 installation media does has efi files it's not following UEFI removable bootable device spec and I'm currently failed to make it boot).
The key is to extract the `bootmgfw.efi` file from `sources/install.wim` and move it to `EFI/Boot/Bootx64.efi`.
Downside is that this relies on [p7zip](http://p7zip.sourceforge.net/) for file extraction (and thus introduces a new dependency).
Also, I'm not completely sure if my Windows 7 detection mechanism is correct:
1. I assumed that the `MinServer` value in in `sources/cversion.ini` begins with `7` if we're dealing with Windows 7 and …
> Add EFI boot support for Windows 7 64-Bit

- debian/rules
Currently `debian/rules` hardcoded to use 8 build jobs in `make`'s invocation, it should rather be defined as `dpkg-buildpackage`'s --jobs parameter by user instead.
> Debian packaging - don't hardcode parallel building, let user specify themselves instead

- src/winusb.1
> Fix `winusb` manpage's typo

- Makefile.am
.keep file is needed because Git doesn't allow empty folders. This fixes issue #117.
> Fix unneeded m4 include

- README.md
Fedora 22 has gtk 2 by default, and I also needed the dh-autoreconf.noarch package.
> add additional dependencies for Fedora 22

- src/MainPanel.cpp
Fix typo in the message box for cancelling the installation.
Signed-off-by: Leon Anavi <leon@anavi.org>
> src/MainPanel.cpp: Fix typo

- README.md
Hello,
I'm the package maintainer for WoeUSB in Fedora 25+. I figured I'd mention it in the read me as one of the third-party distributions in the read me.
> Mention that WoeUSB is packaged for Fedora in the read me

- src/woeusb
Change partition for UEFI-NTFS to 1024 sectors, leaving 512KB for newer versions of UEFI-NTFS which doubled in size.
> Double size of UEFI-NTFS partition to accomodate new size

- src/woeusb
If source directory contain file with size grater than 4GB, script will end with message:
> Error: File <file> is larger than that supported by the fat32 filesystem. Use NTFS (--target-filesystem NTFS).
> Added check for files bigger than 4GB

- src/woeusb
This seems intended to prevent someone from passing both --device and --partition arguments on the cli.. but the way it's currently written if one were to pass --partition, the tool would fail due to "mutual exclusivity" despite NOT having passed the --device argument
Apologies, if I've misunderstood how this works.. but I edited my copy and was able to successfully boot from a partition, whereas before I got this error message.
> Update check for passing --device & --partition

- README.md
WoeUSB is available in official openSUSE Tumbleweed and openSUSE Leap 15.0 repository.
> Add openSUSE packages

- src/MainPanel.cpp
- src/MainPanel.hpp
This PR allows users to select between `FAT` and `NTFS` file system format when writing the main partition to the USB - squashed lots of previous commits from a previous PR.
> Add file system selection to woeusbgui (squashed)

- src/woeusb
When 
`    echo 0 > /proc/sys/vm/dirty_background_bytes`
or
`    echo 0 > /proc/sys/vm/dirty_bytes`
failed and return 1 (file was probably locked because it existed and was writable) then woeusb crashed with message 'program is prematurely aborted' but everything works.
> Fix issue 272 - error when echo 0 into dirty_background_bytes and dirty_bytes

- src/woeusb
The fstype_options variable can contain several options, and thus
should not be quoted.
Closes #299
Signed-off-by: Chris Halls <halls@debian.org>
> woeusb: Fix mount error (#299)

- debian/control
The current 'testing' Debian does not provide `libwxgtk2.8-dev` or `libwxgtk3.0-dev` packages. However, `libwxgtk3.0-gtk3-dev` is available.
This PR adds this build-dependancy package to be installable on 'Debian testing'.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
This PR fixes #295.
> Update Debian build dependancy
